"""
PDF report generator for the Placement Analytics Dashboard.

Uses fpdf2 to compose a multi-page report and kaleido (via Plotly) to
rasterise each chart as a PNG image embedded in the PDF.
"""

from __future__ import annotations

import io
import tempfile
from datetime import datetime
from typing import Dict, List, Optional, Tuple

import pandas as pd
import plotly.graph_objects as go
from fpdf import FPDF

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
_PAGE_W = 210  # A4 width in mm
_PAGE_H = 297  # A4 height in mm
_MARGIN = 15
_CONTENT_W = _PAGE_W - 2 * _MARGIN
_IMG_SCALE = 2  # retina-quality export

_COLOR_PRIMARY = (30, 41, 59)       # slate-800
_COLOR_ACCENT = (16, 185, 129)      # emerald-500
_COLOR_TEXT = (15, 23, 42)           # slate-900
_COLOR_SECONDARY = (100, 116, 139)  # slate-500
_COLOR_BORDER = (226, 232, 240)     # slate-200
_COLOR_WHITE = (255, 255, 255)
_COLOR_LIGHT_BG = (248, 250, 252)   # slate-50


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _fig_to_bytes(fig: go.Figure, width: int = 700, height: int = 400) -> bytes:
    """Export a Plotly figure to PNG bytes via kaleido."""
    return fig.to_image(format="png", width=width * _IMG_SCALE, height=height * _IMG_SCALE, scale=1)


def _fmt_delta(value: Optional[float], suffix: str = "%") -> str:
    if value is None:
        return "N/A"
    sign = "+" if value > 0 else ""
    return f"{sign}{value}{suffix}"


# ---------------------------------------------------------------------------
# PDF builder
# ---------------------------------------------------------------------------
class PlacementPDF(FPDF):
    """Custom FPDF subclass with header/footer branding."""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.set_auto_page_break(auto=True, margin=20)

    # ----- header -----
    def header(self):
        if self.page_no() == 1:
            return  # custom cover on first page
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*_COLOR_SECONDARY)
        self.cell(0, 8, "Placement Analytics Report", align="L")
        self.set_font("Helvetica", "", 9)
        self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        # thin rule
        self.set_draw_color(*_COLOR_BORDER)
        self.line(self.l_margin, self.get_y(), _PAGE_W - self.r_margin, self.get_y())
        self.ln(4)

    # ----- footer -----
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*_COLOR_SECONDARY)
        self.cell(0, 8, "Generated by Placement Analytics Dashboard", align="C")


def generate_pdf(df: pd.DataFrame, metrics: Dict) -> bytes:
    """Build the full PDF report and return it as bytes.

    Args:
        df: Filtered DataFrame currently displayed on the dashboard.
        metrics: Dict returned by ``compute_derived_metrics``.

    Returns:
        PDF file content as ``bytes``, ready for ``st.download_button``.
    """
    # Lazy import to avoid circular dependency (components -> utils -> components)
    from components.visualizations import (  # noqa: E402
        build_branch_comparison,
        build_growth_heatmap,
        build_internship_conversion,
        build_job_role_distribution,
        build_package_distribution,
        build_package_trends,
        build_placement_trends,
        build_scatter_performance,
        build_students_placed_bar,
        build_top_companies,
    )

    pdf = PlacementPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margin(_MARGIN)

    # ==================== Page 1 – Cover ====================
    pdf.add_page()
    pdf.ln(40)

    # Title
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*_COLOR_PRIMARY)
    pdf.cell(0, 14, "Placement Analytics", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(*_COLOR_SECONDARY)
    pdf.cell(0, 10, "Comprehensive Report", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(6)

    # Accent line
    pdf.set_draw_color(*_COLOR_ACCENT)
    pdf.set_line_width(0.8)
    cx = _PAGE_W / 2
    pdf.line(cx - 30, pdf.get_y(), cx + 30, pdf.get_y())
    pdf.ln(10)

    # Date & filter summary
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*_COLOR_SECONDARY)
    pdf.cell(0, 7, f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}", align="C", new_x="LMARGIN", new_y="NEXT")

    years = sorted(df["year"].unique())
    branches = sorted(df["branch"].unique())
    pdf.cell(0, 7, f"Years: {', '.join(str(y) for y in years)}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Branches: {', '.join(branches)}", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(16)

    # ---------- KPI cards ----------
    _render_kpi_cards(pdf, metrics)

    # ==================== Chart pages ====================
    chart_builders: List[Tuple[str, callable]] = [
        ("Placement Trends Over Years", build_placement_trends),
        ("Students Placed vs Unplaced by Year", build_students_placed_bar),
        ("Branch-wise Placement Rate", build_branch_comparison),
        ("Package Distribution by Branch", build_package_distribution),
        ("Package Trends Over Years", build_package_trends),
        ("Placement Rate vs Avg Package", build_scatter_performance),
        ("Top Recruiting Companies", build_top_companies),
        ("Job Role Distribution", build_job_role_distribution),
        ("Internship Conversion vs Placement Rate", build_internship_conversion),
        ("Placement Rate by Branch & Year", build_growth_heatmap),
    ]

    for title, builder in chart_builders:
        fig, insight = builder(df)
        if fig is None:
            continue
        _add_chart_page(pdf, title, fig, insight)

    # ==================== Data table page ====================
    _add_data_table(pdf, df)

    # ==================== Output ====================
    return bytes(pdf.output())


# ---------------------------------------------------------------------------
# Internal layout helpers
# ---------------------------------------------------------------------------
def _render_kpi_cards(pdf: PlacementPDF, m: Dict) -> None:
    """Draw four KPI boxes on the current page."""
    cards = [
        ("Total Placements", f"{m['total_placed']:,}", _fmt_delta(m.get("yoy_placed_change"), "% YoY")),
        ("Placement Rate", f"{m['overall_placement_pct']}%", _fmt_delta(m.get("pct_delta"), " pp")),
        ("Highest Package", f"{m['highest_package']} LPA", m["highest_package_branch"]),
        ("Avg Package", f"{m['weighted_avg_package']} LPA", _fmt_delta(m.get("yoy_avg_pkg_change"), "% YoY")),
    ]

    card_w = (_CONTENT_W - 3 * 4) / 4  # 4 cards, 4mm gap
    card_h = 28
    x_start = _MARGIN
    y = pdf.get_y()

    for i, (label, value, delta) in enumerate(cards):
        x = x_start + i * (card_w + 4)

        # Card background
        pdf.set_fill_color(*_COLOR_WHITE)
        pdf.set_draw_color(*_COLOR_BORDER)
        pdf.rect(x, y, card_w, card_h, style="DF")

        # Label
        pdf.set_xy(x + 3, y + 3)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*_COLOR_SECONDARY)
        pdf.cell(card_w - 6, 4, label.upper(), new_x="LMARGIN", new_y="NEXT")

        # Value
        pdf.set_xy(x + 3, y + 9)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(*_COLOR_TEXT)
        pdf.cell(card_w - 6, 7, value, new_x="LMARGIN", new_y="NEXT")

        # Delta
        pdf.set_xy(x + 3, y + 19)
        pdf.set_font("Helvetica", "", 7.5)
        if delta and delta.startswith("+"):
            pdf.set_text_color(16, 185, 129)   # green
        elif delta and delta.startswith("-"):
            pdf.set_text_color(239, 68, 68)     # red
        else:
            pdf.set_text_color(*_COLOR_SECONDARY)
        pdf.cell(card_w - 6, 4, delta, new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(y + card_h + 6)


def _add_chart_page(pdf: PlacementPDF, title: str, fig: go.Figure, insight: str) -> None:
    """Add a new page with a chart image and insight text."""
    pdf.add_page()

    # Section title
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_COLOR_PRIMARY)
    pdf.cell(0, 9, title, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Render chart to image
    img_bytes = _fig_to_bytes(fig, width=700, height=400)

    # Write to a temp file (fpdf2 can read from path or bytes via io)
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        tmp.write(img_bytes)
        tmp_path = tmp.name

    img_w = _CONTENT_W
    img_h = img_w * 400 / 700  # maintain aspect ratio
    pdf.image(tmp_path, x=_MARGIN, y=pdf.get_y(), w=img_w, h=img_h)
    pdf.set_y(pdf.get_y() + img_h + 4)

    # Insight
    if insight:
        # Light background box for insight
        box_y = pdf.get_y()
        pdf.set_fill_color(*_COLOR_LIGHT_BG)
        pdf.set_draw_color(*_COLOR_BORDER)

        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*_COLOR_SECONDARY)
        # Measure text height
        text_h = pdf.get_string_width(insight) / _CONTENT_W * 5 + 10
        text_h = max(text_h, 10)
        pdf.rect(_MARGIN, box_y, _CONTENT_W, text_h, style="DF")
        pdf.set_xy(_MARGIN + 4, box_y + 2)
        pdf.multi_cell(_CONTENT_W - 8, 5, f"Insight: {insight}")

    # Clean up temp file
    import os
    try:
        os.unlink(tmp_path)
    except OSError:
        pass


def _add_data_table(pdf: PlacementPDF, df: pd.DataFrame) -> None:
    """Add a page with a summary data table."""
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*_COLOR_PRIMARY)
    pdf.cell(0, 9, "Data Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Build a branch x year summary table
    summary = df.groupby(["branch", "year"], as_index=False).agg(
        placed=("placed_students", "sum"),
        total=("total_students", "sum"),
        avg_pkg=("avg_package_LPA", "mean"),
        pct=("placement_percentage", "mean"),
    )
    summary["avg_pkg"] = summary["avg_pkg"].round(1)
    summary["pct"] = summary["pct"].round(1)

    cols = ["branch", "year", "placed", "total", "pct", "avg_pkg"]
    headers = ["Branch", "Year", "Placed", "Total", "Placement %", "Avg Pkg (LPA)"]
    col_widths = [40, 18, 20, 20, 28, 30]

    # Header row
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_fill_color(*_COLOR_PRIMARY)
    pdf.set_text_color(*_COLOR_WHITE)
    for header, w in zip(headers, col_widths):
        pdf.cell(w, 7, header, border=0, fill=True, align="C")
    pdf.ln()

    # Data rows
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*_COLOR_TEXT)
    fill = False
    for _, row in summary.iterrows():
        if fill:
            pdf.set_fill_color(*_COLOR_LIGHT_BG)
        else:
            pdf.set_fill_color(*_COLOR_WHITE)
        for col, w in zip(cols, col_widths):
            val = row[col]
            if isinstance(val, float):
                val = f"{val:.1f}"
            else:
                val = str(val)
            align = "L" if col == "branch" else "C"
            pdf.cell(w, 6, val, border=0, fill=True, align=align)
        pdf.ln()
        fill = not fill
